import type { TThemeMode } from '@/types/app';
import 'monaco-editor/esm/nls.messages.zh-cn.js';
import 'monaco-editor/esm/vs/basic-languages/shell/shell.contribution';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
import 'monaco-editor/min/vs/editor/editor.main.css';

type TMonacoEnvironment = {
  getWorker: () => Worker;
};

type TResolvedMonacoTheme = 'dark' | 'light';
type TMonacoThemeName = 'sh-dark' | 'sh-light';
type TMonacoThemeDefinition = monaco.editor.IStandaloneThemeData;

const globalScope = self as typeof self & {
  MonacoEnvironment?: TMonacoEnvironment;
  __SH_EDITOR_MONACO_READY__?: boolean;
};

const resolveMonacoThemeMode = (theme: TThemeMode): TResolvedMonacoTheme =>
  theme === 'light' ? 'light' : 'dark';

const resolveMonacoThemeName = (theme: TThemeMode): TMonacoThemeName =>
  resolveMonacoThemeMode(theme) === 'light' ? 'sh-light' : 'sh-dark';

const createDarkThemeDefinition = (): TMonacoThemeDefinition => ({
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '4d5166', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c4b5fd' },
    { token: 'string', foreground: '86efac' },
    { token: 'number', foreground: 'fca5a5' },
    { token: 'delimiter', foreground: '737780' },
    { token: 'variable', foreground: 'fcd34d' },
    { token: 'type', foreground: '7dd3fc' },
    { token: 'function', foreground: '7dd3fc' },
    { token: 'operator', foreground: 'a0a7b0' },
  ],
  colors: {
    focusBorder: '#6f7cff',
    foreground: '#f3f4f6',
    descriptionForeground: '#949aa6',
    errorForeground: '#ff6b7a',
    'icon.foreground': '#c9ced8',
    'selection.background': '#20242c',
    'widget.shadow': '#0308146b',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#ffffff1a',
    'scrollbarSlider.hoverBackground': '#ffffff29',
    'scrollbarSlider.activeBackground': '#ffffff3d',
    'badge.background': '#273b85',
    'badge.foreground': '#f3f4f6',
    'progressBar.background': '#6f7cff',
    'list.hoverBackground': '#ffffff0a',
    'list.hoverForeground': '#f3f4f6',
    'list.activeSelectionBackground': '#20242c',
    'list.activeSelectionForeground': '#f3f4f6',
    'list.inactiveSelectionBackground': '#ffffff08',
    'list.inactiveSelectionForeground': '#c9ced8',
    'list.focusBackground': '#20242c',
    'list.focusForeground': '#f3f4f6',
    'list.highlightForeground': '#7c89ff',
    'list.dropBackground': '#5e6ad238',
    'menu.background': '#15191e',
    'menu.foreground': '#f3f4f6',
    'menu.selectionBackground': '#20242c',
    'menu.selectionForeground': '#f3f4f6',
    'menu.selectionBorder': '#6f7cff45',
    'menu.separatorBackground': '#ffffff0f',
    'menu.border': '#ffffff14',
    'editorActionList.background': '#15191e',
    'editorActionList.foreground': '#f3f4f6',
    'editorActionList.focusBackground': '#20242c',
    'editorActionList.focusForeground': '#f3f4f6',
    'editor.background': '#0f0f12',
    'editor.foreground': '#f3f4f6',
    'editorLineNumber.foreground': '#383c44',
    'editorLineNumber.activeForeground': '#cccdd8',
    'editorCursor.foreground': '#a78bfa',
    'editor.selectionBackground': '#5e6ad242',
    'editor.inactiveSelectionBackground': '#5e6ad22a',
    'editor.selectionHighlightBackground': '#ffffff0d',
    'editor.wordHighlightBackground': '#ffffff12',
    'editor.wordHighlightStrongBackground': '#5e6ad226',
    'editor.rangeHighlightBackground': '#ffffff08',
    'editor.findMatchBackground': '#6f7cff40',
    'editor.findMatchBorder': '#6f7cff7d',
    'editor.findMatchHighlightBackground': '#ffffff12',
    'editor.findRangeHighlightBackground': '#5e6ad218',
    'editor.lineHighlightBackground': '#ffffff08',
    'editor.lineHighlightBorder': '#00000000',
    'editorLink.activeForeground': '#9aa6ff',
    'editorWhitespace.foreground': '#ffffff20',
    'editorIndentGuide.background1': '#ffffff14',
    'editorIndentGuide.activeBackground1': '#ffffff24',
    'editorBracketMatch.background': '#5e6ad218',
    'editorBracketMatch.border': '#6f7cff73',
    'editor.foldBackground': '#5e6ad21f',
    'editorGutter.background': '#0f0f12',
    'editorGutter.modifiedBackground': '#7c89ff',
    'editorGutter.addedBackground': '#86efac',
    'editorGutter.deletedBackground': '#fb7185',
    'editorOverviewRuler.border': '#00000000',
    'editorOverviewRuler.errorForeground': '#ff6b7a70',
    'editorOverviewRuler.warningForeground': '#f3c96966',
    'editorOverviewRuler.infoForeground': '#6f7cff66',
    'editorError.foreground': '#ff6b7a',
    'editorWarning.foreground': '#f3c969',
    'editorInfo.foreground': '#6f7cff',
    'editorHint.foreground': '#8e96a3',
    'editorLightBulb.foreground': '#f3c969',
    'editorLightBulbAutoFix.foreground': '#6f7cff',
    'editorWidget.background': '#15191e',
    'editorWidget.foreground': '#f3f4f6',
    'editorWidget.border': '#ffffff14',
    'editorSuggestWidget.background': '#15191e',
    'editorSuggestWidget.border': '#ffffff14',
    'editorSuggestWidget.foreground': '#f3f4f6',
    'editorSuggestWidget.selectedBackground': '#20242c',
    'editorSuggestWidget.selectedForeground': '#f3f4f6',
    'editorSuggestWidget.highlightForeground': '#7c89ff',
    'editorSuggestWidget.focusHighlightForeground': '#9aa6ff',
    'editorSuggestWidgetStatus.foreground': '#949aa6',
    'editorHoverWidget.background': '#15191e',
    'editorHoverWidget.foreground': '#f3f4f6',
    'editorHoverWidget.border': '#ffffff14',
    'editorHoverWidget.statusBarBackground': '#111419',
    editorHoverWidgetHighlightForeground: '#7c89ff',
    'editorMarkerNavigation.background': '#15191e',
    'editorMarkerNavigationError.background': '#2a171d',
    'editorMarkerNavigationError.headerBackground': '#4f1e29',
    'editorMarkerNavigationWarning.background': '#2b2414',
    'editorMarkerNavigationWarning.headerBackground': '#59481b',
    'editorMarkerNavigationInfo.background': '#171f3f',
    'editorMarkerNavigationInfo.headerBackground': '#23306d',
    'editorMarkerNavigationError.heading': '#ff8d98',
    'editorMarkerNavigationWarning.heading': '#f6d885',
    'editorMarkerNavigationInfo.heading': '#9aa6ff',
    'peekView.border': '#6f7cff45',
    'peekViewEditor.background': '#15191e',
    'peekViewEditor.matchHighlightBackground': '#5e6ad228',
    'peekViewResult.background': '#111419',
    'peekViewResult.selectionBackground': '#20242c',
    'peekViewResult.selectionForeground': '#f3f4f6',
    'peekViewTitle.background': '#111419',
    'peekViewTitleLabel.foreground': '#f3f4f6',
    'peekViewTitleDescription.foreground': '#949aa6',
    'input.background': '#111419',
    'input.foreground': '#f3f4f6',
    'input.border': '#ffffff1a',
    'input.placeholderForeground': '#656b76',
    'inputOption.activeBorder': '#6f7cff',
    'inputOption.activeBackground': '#5e6ad226',
    'inputOption.activeForeground': '#f3f4f6',
    'inputValidation.infoBackground': '#171f3f',
    'inputValidation.infoBorder': '#6f7cff45',
    'inputValidation.warningBackground': '#2b2414',
    'inputValidation.warningBorder': '#f3c96955',
    'inputValidation.errorBackground': '#2a171d',
    'inputValidation.errorBorder': '#ff6b7a66',
    'quickInput.background': '#15191e',
    'quickInput.foreground': '#f3f4f6',
    'quickInputTitle.background': '#111419',
    'quickInputList.focusBackground': '#20242c',
    'quickInputList.focusForeground': '#f3f4f6',
    'pickerGroup.foreground': '#949aa6',
    'pickerGroup.border': '#ffffff0f',
    'keybindingLabel.background': '#111419',
    'keybindingLabel.foreground': '#c9ced8',
    'keybindingLabel.border': '#ffffff14',
    'keybindingLabel.bottomBorder': '#ffffff0f',
    'button.background': '#4c6fff',
    'button.foreground': '#f8fafc',
    'button.hoverBackground': '#5c7cff',
    'button.secondaryBackground': '#20242c',
    'button.secondaryForeground': '#f3f4f6',
    'button.secondaryHoverBackground': '#262c35',
    'textCodeBlock.background': '#111419',
  },
});

const createLightThemeDefinition = (): TMonacoThemeDefinition => ({
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '64748b' },
    { token: 'keyword', foreground: '335cff' },
    { token: 'string', foreground: '15803d' },
    { token: 'number', foreground: 'a16207' },
    { token: 'delimiter', foreground: '334155' },
  ],
  colors: {
    focusBorder: '#335cff',
    foreground: '#111827',
    descriptionForeground: '#64748b',
    errorForeground: '#d92d4f',
    'icon.foreground': '#334155',
    'selection.background': '#eef2f8',
    'widget.shadow': '#0f172a1f',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#0f172a1f',
    'scrollbarSlider.hoverBackground': '#0f172a33',
    'scrollbarSlider.activeBackground': '#335cff4d',
    'badge.background': '#335cff',
    'badge.foreground': '#ffffff',
    'progressBar.background': '#335cff',
    'list.hoverBackground': '#f8fafc',
    'list.hoverForeground': '#111827',
    'list.activeSelectionBackground': '#eef2f8',
    'list.activeSelectionForeground': '#111827',
    'list.inactiveSelectionBackground': '#f8fafc',
    'list.inactiveSelectionForeground': '#334155',
    'list.focusBackground': '#eef2f8',
    'list.focusForeground': '#111827',
    'list.highlightForeground': '#335cff',
    'list.dropBackground': '#4c6fff24',
    'menu.background': '#f5f7fb',
    'menu.foreground': '#111827',
    'menu.selectionBackground': '#eef2f8',
    'menu.selectionForeground': '#111827',
    'menu.selectionBorder': '#335cff26',
    'menu.separatorBackground': '#0f172a14',
    'menu.border': '#0f172a14',
    'editorActionList.background': '#f5f7fb',
    'editorActionList.foreground': '#111827',
    'editorActionList.focusBackground': '#eef2f8',
    'editorActionList.focusForeground': '#111827',
    'editor.background': '#ffffff',
    'editor.foreground': '#111827',
    'editorLineNumber.foreground': '#94a3b8',
    'editorLineNumber.activeForeground': '#334155',
    'editorCursor.foreground': '#335cff',
    'editor.selectionBackground': '#4c6fff2e',
    'editor.inactiveSelectionBackground': '#4c6fff1c',
    'editor.selectionHighlightBackground': '#0f172a0c',
    'editor.wordHighlightBackground': '#0f172a12',
    'editor.wordHighlightStrongBackground': '#4c6fff20',
    'editor.rangeHighlightBackground': '#0f172a08',
    'editor.findMatchBackground': '#335cff29',
    'editor.findMatchBorder': '#335cff66',
    'editor.findMatchHighlightBackground': '#0f172a10',
    'editor.findRangeHighlightBackground': '#4c6fff12',
    'editor.lineHighlightBackground': '#0f172a06',
    'editor.lineHighlightBorder': '#00000000',
    'editorLink.activeForeground': '#335cff',
    'editorWhitespace.foreground': '#0f172a24',
    'editorIndentGuide.background1': '#0f172a14',
    'editorIndentGuide.activeBackground1': '#0f172a26',
    'editorBracketMatch.background': '#4c6fff12',
    'editorBracketMatch.border': '#335cff59',
    'editor.foldBackground': '#4c6fff12',
    'editorGutter.background': '#ffffff',
    'editorGutter.modifiedBackground': '#335cff',
    'editorGutter.addedBackground': '#16a34a',
    'editorGutter.deletedBackground': '#e11d48',
    'editorOverviewRuler.border': '#00000000',
    'editorOverviewRuler.errorForeground': '#d92d4f55',
    'editorOverviewRuler.warningForeground': '#ca8a0455',
    'editorOverviewRuler.infoForeground': '#335cff4d',
    'editorError.foreground': '#d92d4f',
    'editorWarning.foreground': '#ca8a04',
    'editorInfo.foreground': '#335cff',
    'editorHint.foreground': '#64748b',
    'editorLightBulb.foreground': '#ca8a04',
    'editorLightBulbAutoFix.foreground': '#335cff',
    'editorWidget.background': '#f5f7fb',
    'editorWidget.foreground': '#111827',
    'editorWidget.border': '#0f172a14',
    'editorSuggestWidget.background': '#f5f7fb',
    'editorSuggestWidget.border': '#0f172a14',
    'editorSuggestWidget.foreground': '#111827',
    'editorSuggestWidget.selectedBackground': '#eef2f8',
    'editorSuggestWidget.selectedForeground': '#111827',
    'editorSuggestWidget.highlightForeground': '#335cff',
    'editorSuggestWidget.focusHighlightForeground': '#335cff',
    'editorSuggestWidgetStatus.foreground': '#64748b',
    'editorHoverWidget.background': '#f5f7fb',
    'editorHoverWidget.foreground': '#111827',
    'editorHoverWidget.border': '#0f172a14',
    'editorHoverWidget.statusBarBackground': '#eef2f8',
    editorHoverWidgetHighlightForeground: '#335cff',
    'editorMarkerNavigation.background': '#f5f7fb',
    'editorMarkerNavigationError.background': '#fff1f4',
    'editorMarkerNavigationError.headerBackground': '#ffdbe3',
    'editorMarkerNavigationWarning.background': '#fff7e8',
    'editorMarkerNavigationWarning.headerBackground': '#ffe7b2',
    'editorMarkerNavigationInfo.background': '#eff5ff',
    'editorMarkerNavigationInfo.headerBackground': '#dbe7ff',
    'editorMarkerNavigationError.heading': '#b42318',
    'editorMarkerNavigationWarning.heading': '#a16207',
    'editorMarkerNavigationInfo.heading': '#335cff',
    'peekView.border': '#335cff26',
    'peekViewEditor.background': '#f5f7fb',
    'peekViewEditor.matchHighlightBackground': '#4c6fff18',
    'peekViewResult.background': '#eef2f8',
    'peekViewResult.selectionBackground': '#dbe7ff',
    'peekViewResult.selectionForeground': '#111827',
    'peekViewTitle.background': '#eef2f8',
    'peekViewTitleLabel.foreground': '#111827',
    'peekViewTitleDescription.foreground': '#64748b',
    'input.background': '#ffffff',
    'input.foreground': '#111827',
    'input.border': '#0f172a14',
    'input.placeholderForeground': '#94a3b8',
    'inputOption.activeBorder': '#335cff',
    'inputOption.activeBackground': '#4c6fff14',
    'inputOption.activeForeground': '#111827',
    'inputValidation.infoBackground': '#eff5ff',
    'inputValidation.infoBorder': '#335cff26',
    'inputValidation.warningBackground': '#fff7e8',
    'inputValidation.warningBorder': '#d4a72c55',
    'inputValidation.errorBackground': '#fff1f4',
    'inputValidation.errorBorder': '#d92d4f59',
    'quickInput.background': '#f5f7fb',
    'quickInput.foreground': '#111827',
    'quickInputTitle.background': '#eef2f8',
    'quickInputList.focusBackground': '#eef2f8',
    'quickInputList.focusForeground': '#111827',
    'pickerGroup.foreground': '#64748b',
    'pickerGroup.border': '#0f172a14',
    'keybindingLabel.background': '#ffffff',
    'keybindingLabel.foreground': '#334155',
    'keybindingLabel.border': '#0f172a14',
    'keybindingLabel.bottomBorder': '#0f172a10',
    'button.background': '#335cff',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#4c6fff',
    'button.secondaryBackground': '#eef2f8',
    'button.secondaryForeground': '#111827',
    'button.secondaryHoverBackground': '#e2e8f0',
    'textCodeBlock.background': '#eef2f8',
  },
});

const MONACO_THEMES: Record<TResolvedMonacoTheme, TMonacoThemeDefinition> = {
  dark: createDarkThemeDefinition(),
  light: createLightThemeDefinition(),
};

const registerMonacoThemes = (): void => {
  monaco.editor.defineTheme('sh-dark', MONACO_THEMES.dark);
  monaco.editor.defineTheme('sh-light', MONACO_THEMES.light);
};

if (!globalScope.MonacoEnvironment) {
  globalScope.MonacoEnvironment = {
    getWorker() {
      return new editorWorker();
    },
  };
}

if (!globalScope.__SH_EDITOR_MONACO_READY__) {
  registerMonacoThemes();
  globalScope.__SH_EDITOR_MONACO_READY__ = true;
}

const applyMonacoTheme = (theme: TThemeMode): void => {
  monaco.editor.setTheme(resolveMonacoThemeName(theme));
};

export { applyMonacoTheme, monaco };
